//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: game_pb.proto
namespace gprotocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgPing")]
  public partial class MsgPing : global::ProtoBuf.IExtensible
  {
    public MsgPing() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgPong")]
  public partial class MsgPong : global::ProtoBuf.IExtensible
  {
    public MsgPong() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgSyncTank")]
  public partial class MsgSyncTank : global::ProtoBuf.IExtensible
  {
    public MsgSyncTank() {}
    
    private float _x = default(float);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private float _z = default(float);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float z
    {
      get { return _z; }
      set { _z = value; }
    }
    private float _ex = default(float);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"ex", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float ex
    {
      get { return _ex; }
      set { _ex = value; }
    }
    private float _ey = default(float);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"ey", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float ey
    {
      get { return _ey; }
      set { _ey = value; }
    }
    private float _ez = default(float);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"ez", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float ez
    {
      get { return _ez; }
      set { _ez = value; }
    }
    private float _turretY = default(float);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"turretY", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float turretY
    {
      get { return _turretY; }
      set { _turretY = value; }
    }
    private string _id = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgFire")]
  public partial class MsgFire : global::ProtoBuf.IExtensible
  {
    public MsgFire() {}
    
    private float _x = default(float);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private float _z = default(float);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float z
    {
      get { return _z; }
      set { _z = value; }
    }
    private float _ex = default(float);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"ex", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float ex
    {
      get { return _ex; }
      set { _ex = value; }
    }
    private float _ey = default(float);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"ey", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float ey
    {
      get { return _ey; }
      set { _ey = value; }
    }
    private float _ez = default(float);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"ez", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float ez
    {
      get { return _ez; }
      set { _ez = value; }
    }
    private string _id = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgHit")]
  public partial class MsgHit : global::ProtoBuf.IExtensible
  {
    public MsgHit() {}
    
    private string _targetId = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"targetId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string targetId
    {
      get { return _targetId; }
      set { _targetId = value; }
    }
    private float _x = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y = default(float);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private float _z = default(float);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float z
    {
      get { return _z; }
      set { _z = value; }
    }
    private string _id = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }
    private float _hp = default(float);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    private float _damage = default(float);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"damage", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float damage
    {
      get { return _damage; }
      set { _damage = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgGetAchieve")]
  public partial class MsgGetAchieve : global::ProtoBuf.IExtensible
  {
    public MsgGetAchieve() {}
    
    private int _win = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"win", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int win
    {
      get { return _win; }
      set { _win = value; }
    }
    private int _lost = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"lost", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int lost
    {
      get { return _lost; }
      set { _lost = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoomInfo")]
  public partial class RoomInfo : global::ProtoBuf.IExtensible
  {
    public RoomInfo() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _count = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int count
    {
      get { return _count; }
      set { _count = value; }
    }
    private int _status = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgGetRoomList")]
  public partial class MsgGetRoomList : global::ProtoBuf.IExtensible
  {
    public MsgGetRoomList() {}
    
    private readonly global::System.Collections.Generic.List<RoomInfo> _rooms = new global::System.Collections.Generic.List<RoomInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"rooms", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<RoomInfo> rooms
    {
      get { return _rooms; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgCreateRoom")]
  public partial class MsgCreateRoom : global::ProtoBuf.IExtensible
  {
    public MsgCreateRoom() {}
    
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgEnterRoom")]
  public partial class MsgEnterRoom : global::ProtoBuf.IExtensible
  {
    public MsgEnterRoom() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerInfo")]
  public partial class PlayerInfo : global::ProtoBuf.IExtensible
  {
    public PlayerInfo() {}
    
    private string _id = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _camp = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"camp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int camp
    {
      get { return _camp; }
      set { _camp = value; }
    }
    private int _win = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"win", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int win
    {
      get { return _win; }
      set { _win = value; }
    }
    private int _lost = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"lost", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int lost
    {
      get { return _lost; }
      set { _lost = value; }
    }
    private int _isOwner = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"isOwner", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int isOwner
    {
      get { return _isOwner; }
      set { _isOwner = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgGetRoomInfo")]
  public partial class MsgGetRoomInfo : global::ProtoBuf.IExtensible
  {
    public MsgGetRoomInfo() {}
    
    private readonly global::System.Collections.Generic.List<PlayerInfo> _players = new global::System.Collections.Generic.List<PlayerInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"players", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PlayerInfo> players
    {
      get { return _players; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgLeaveRoom")]
  public partial class MsgLeaveRoom : global::ProtoBuf.IExtensible
  {
    public MsgLeaveRoom() {}
    
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgStartBattle")]
  public partial class MsgStartBattle : global::ProtoBuf.IExtensible
  {
    public MsgStartBattle() {}
    
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgGetText")]
  public partial class MsgGetText : global::ProtoBuf.IExtensible
  {
    public MsgGetText() {}
    
    private string _text = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"text", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string text
    {
      get { return _text; }
      set { _text = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgSaveText")]
  public partial class MsgSaveText : global::ProtoBuf.IExtensible
  {
    public MsgSaveText() {}
    
    private string _text = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"text", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string text
    {
      get { return _text; }
      set { _text = value; }
    }
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgRegister")]
  public partial class MsgRegister : global::ProtoBuf.IExtensible
  {
    public MsgRegister() {}
    
    private string _username = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"username", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string username
    {
      get { return _username; }
      set { _username = value; }
    }
    private string _password = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgLogin")]
  public partial class MsgLogin : global::ProtoBuf.IExtensible
  {
    public MsgLogin() {}
    
    private string _username = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"username", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string username
    {
      get { return _username; }
      set { _username = value; }
    }
    private string _password = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgKick")]
  public partial class MsgKick : global::ProtoBuf.IExtensible
  {
    public MsgKick() {}
    
    private int _reason = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"reason", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int reason
    {
      get { return _reason; }
      set { _reason = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgMove")]
  public partial class MsgMove : global::ProtoBuf.IExtensible
  {
    public MsgMove() {}
    
    private int _x = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int x
    {
      get { return _x; }
      set { _x = value; }
    }
    private int _y = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int y
    {
      get { return _y; }
      set { _y = value; }
    }
    private int _z = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int z
    {
      get { return _z; }
      set { _z = value; }
    }
    private float _ox = default(float);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"ox", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float ox
    {
      get { return _ox; }
      set { _ox = value; }
    }
    private float _oy = default(float);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"oy", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float oy
    {
      get { return _oy; }
      set { _oy = value; }
    }
    private float _tx = default(float);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"tx", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float tx
    {
      get { return _tx; }
      set { _tx = value; }
    }
    private float _ty = default(float);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"ty", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float ty
    {
      get { return _ty; }
      set { _ty = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TankInfo")]
  public partial class TankInfo : global::ProtoBuf.IExtensible
  {
    public TankInfo() {}
    
    private string _id = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _camp = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"camp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int camp
    {
      get { return _camp; }
      set { _camp = value; }
    }
    private float _hp = default(float);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    private float _att = default(float);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"att", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float att
    {
      get { return _att; }
      set { _att = value; }
    }
    private float _def = default(float);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"def", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float def
    {
      get { return _def; }
      set { _def = value; }
    }
    private float _x = default(float);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y = default(float);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private float _z = default(float);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float z
    {
      get { return _z; }
      set { _z = value; }
    }
    private float _ex = default(float);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"ex", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float ex
    {
      get { return _ex; }
      set { _ex = value; }
    }
    private float _ey = default(float);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"ey", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float ey
    {
      get { return _ey; }
      set { _ey = value; }
    }
    private float _ez = default(float);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"ez", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float ez
    {
      get { return _ez; }
      set { _ez = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgEnterBattle")]
  public partial class MsgEnterBattle : global::ProtoBuf.IExtensible
  {
    public MsgEnterBattle() {}
    
    private readonly global::System.Collections.Generic.List<TankInfo> _tanks = new global::System.Collections.Generic.List<TankInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"tanks", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<TankInfo> tanks
    {
      get { return _tanks; }
    }
  
    private int _mapId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"mapId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int mapId
    {
      get { return _mapId; }
      set { _mapId = value; }
    }
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgBattleResult")]
  public partial class MsgBattleResult : global::ProtoBuf.IExtensible
  {
    public MsgBattleResult() {}
    
    private int _winCamp = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"winCamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int winCamp
    {
      get { return _winCamp; }
      set { _winCamp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgLeaveBattle")]
  public partial class MsgLeaveBattle : global::ProtoBuf.IExtensible
  {
    public MsgLeaveBattle() {}
    
    private string _id = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqUserLogin")]
  public partial class ReqUserLogin : global::ProtoBuf.IExtensible
  {
    public ReqUserLogin() {}
    
    private string _uname;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uname
    {
      get { return _uname; }
      set { _uname = value; }
    }
    private string _upwd;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"upwd", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string upwd
    {
      get { return _upwd; }
      set { _upwd = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResUserLogin")]
  public partial class ResUserLogin : global::ProtoBuf.IExtensible
  {
    public ResUserLogin() {}
    
    private int _status;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    private AccountInfoComponent _uinfo = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"uinfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public AccountInfoComponent uinfo
    {
      get { return _uinfo; }
      set { _uinfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqGuestLogin")]
  public partial class ReqGuestLogin : global::ProtoBuf.IExtensible
  {
    public ReqGuestLogin() {}
    
    private string _guestKey;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"guestKey", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string guestKey
    {
      get { return _guestKey; }
      set { _guestKey = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AccountInfo")]
  public partial class AccountInfo : global::ProtoBuf.IExtensible
  {
    public AccountInfo() {}
    
    private string _unick;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"unick", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string unick
    {
      get { return _unick; }
      set { _unick = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResGuestLogin")]
  public partial class ResGuestLogin : global::ProtoBuf.IExtensible
  {
    public ResGuestLogin() {}
    
    private int _status;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    private AccountInfoComponent _uinfo = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"uinfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public AccountInfoComponent uinfo
    {
      get { return _uinfo; }
      set { _uinfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqSelectPlayer")]
  public partial class ReqSelectPlayer : global::ProtoBuf.IExtensible
  {
    public ReqSelectPlayer() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _job;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"job", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int job
    {
      get { return _job; }
      set { _job = value; }
    }
    private string _platform;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"platform", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string platform
    {
      get { return _platform; }
      set { _platform = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipmentProp")]
  public partial class EquipmentProp : global::ProtoBuf.IExtensible
  {
    public EquipmentProp() {}
    
    private int _weaponType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"weaponType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int weaponType
    {
      get { return _weaponType; }
      set { _weaponType = value; }
    }
    private int _amorType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"amorType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int amorType
    {
      get { return _amorType; }
      set { _amorType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResSelectPlayer")]
  public partial class ResSelectPlayer : global::ProtoBuf.IExtensible
  {
    public ResSelectPlayer() {}
    
    private int _status;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    private EquipmentPropComponent _eProp;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"eProp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public EquipmentPropComponent eProp
    {
      get { return _eProp; }
      set { _eProp = value; }
    }
    private PlayerInfoComponent _playerInfo;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"playerInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public PlayerInfoComponent playerInfo
    {
      get { return _playerInfo; }
      set { _playerInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqRuckSack")]
  public partial class ReqRuckSack : global::ProtoBuf.IExtensible
  {
    public ReqRuckSack() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RuckSackItem")]
  public partial class RuckSackItem : global::ProtoBuf.IExtensible
  {
    public RuckSackItem() {}
    
    private int _itemType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"itemType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int itemType
    {
      get { return _itemType; }
      set { _itemType = value; }
    }
    private int _count;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int count
    {
      get { return _count; }
      set { _count = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResRuckSack")]
  public partial class ResRuckSack : global::ProtoBuf.IExtensible
  {
    public ResRuckSack() {}
    
    private int _status;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    private readonly global::System.Collections.Generic.List<RuckSackItem> _items = new global::System.Collections.Generic.List<RuckSackItem>();
    [global::ProtoBuf.ProtoMember(2, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<RuckSackItem> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqPutOnEquipment")]
  public partial class ReqPutOnEquipment : global::ProtoBuf.IExtensible
  {
    public ReqPutOnEquipment() {}
    
    private EquipmentPropComponent _eProp;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"eProp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public EquipmentPropComponent eProp
    {
      get { return _eProp; }
      set { _eProp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResPutEquipment")]
  public partial class ResPutEquipment : global::ProtoBuf.IExtensible
  {
    public ResPutEquipment() {}
    
    private int _status;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqSellGoods")]
  public partial class ReqSellGoods : global::ProtoBuf.IExtensible
  {
    public ReqSellGoods() {}
    
    private int _itemType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"itemType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int itemType
    {
      get { return _itemType; }
      set { _itemType = value; }
    }
    private int _count;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int count
    {
      get { return _count; }
      set { _count = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResSellGoods")]
  public partial class ResSellGoods : global::ProtoBuf.IExtensible
  {
    public ResSellGoods() {}
    
    private int _status;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    private int _itemType = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"itemType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int itemType
    {
      get { return _itemType; }
      set { _itemType = value; }
    }
    private int _count = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int count
    {
      get { return _count; }
      set { _count = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqBuyGoodsWithCoin")]
  public partial class ReqBuyGoodsWithCoin : global::ProtoBuf.IExtensible
  {
    public ReqBuyGoodsWithCoin() {}
    
    private int _itemType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"itemType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int itemType
    {
      get { return _itemType; }
      set { _itemType = value; }
    }
    private int _count;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int count
    {
      get { return _count; }
      set { _count = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResBuyGoodsWithCoin")]
  public partial class ResBuyGoodsWithCoin : global::ProtoBuf.IExtensible
  {
    public ResBuyGoodsWithCoin() {}
    
    private int _status;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    private int _itemType = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"itemType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int itemType
    {
      get { return _itemType; }
      set { _itemType = value; }
    }
    private int _count = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int count
    {
      get { return _count; }
      set { _count = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqEnterScene")]
  public partial class ReqEnterScene : global::ProtoBuf.IExtensible
  {
    public ReqEnterScene() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResEnterScene")]
  public partial class ResEnterScene : global::ProtoBuf.IExtensible
  {
    public ResEnterScene() {}
    
    private int _status;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    private ShapeComponent _shapInfo = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"shapInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ShapeComponent shapInfo
    {
      get { return _shapInfo; }
      set { _shapInfo = value; }
    }
    private TransformComponent _transformInfo = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"transformInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public TransformComponent transformInfo
    {
      get { return _transformInfo; }
      set { _transformInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EntityInfo")]
  public partial class EntityInfo : global::ProtoBuf.IExtensible
  {
    public EntityInfo() {}
    
    private int _hp;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    private int _mp;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"mp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mp
    {
      get { return _mp; }
      set { _mp = value; }
    }
    private int _job;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"job", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int job
    {
      get { return _job; }
      set { _job = value; }
    }
    private int _attack;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"attack", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int attack
    {
      get { return _attack; }
      set { _attack = value; }
    }
    private int _def;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"def", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int def
    {
      get { return _def; }
      set { _def = value; }
    }
    private int _maxHp;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"maxHp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int maxHp
    {
      get { return _maxHp; }
      set { _maxHp = value; }
    }
    private int _maxMp;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"maxMp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int maxMp
    {
      get { return _maxMp; }
      set { _maxMp = value; }
    }
    private long _exp;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private int _height;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"height", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int height
    {
      get { return _height; }
      set { _height = value; }
    }
    private float _speed;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"speed", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float speed
    {
      get { return _speed; }
      set { _speed = value; }
    }
    private float _R;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"R", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float R
    {
      get { return _R; }
      set { _R = value; }
    }
    private float _x;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private float _z;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float z
    {
      get { return _z; }
      set { _z = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerInfoComponent")]
  public partial class PlayerInfoComponent : global::ProtoBuf.IExtensible
  {
    public PlayerInfoComponent() {}
    
    private long _exp;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private int _level;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _HP;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"HP", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int HP
    {
      get { return _HP; }
      set { _HP = value; }
    }
    private int _MP;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"MP", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int MP
    {
      get { return _MP; }
      set { _MP = value; }
    }
    private long _money;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long money
    {
      get { return _money; }
      set { _money = value; }
    }
    private long _coin;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"coin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long coin
    {
      get { return _coin; }
      set { _coin = value; }
    }
    private int _job;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"job", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int job
    {
      get { return _job; }
      set { _job = value; }
    }
    private int _attack;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"attack", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int attack
    {
      get { return _attack; }
      set { _attack = value; }
    }
    private int _def;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"def", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int def
    {
      get { return _def; }
      set { _def = value; }
    }
    private int _maxHp;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"maxHp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int maxHp
    {
      get { return _maxHp; }
      set { _maxHp = value; }
    }
    private int _maxMp;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"maxMp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int maxMp
    {
      get { return _maxMp; }
      set { _maxMp = value; }
    }
    private float _speed;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"speed", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float speed
    {
      get { return _speed; }
      set { _speed = value; }
    }
    private string _position;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string position
    {
      get { return _position; }
      set { _position = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipmentPropComponent")]
  public partial class EquipmentPropComponent : global::ProtoBuf.IExtensible
  {
    public EquipmentPropComponent() {}
    
    private int _weaponType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"weaponType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int weaponType
    {
      get { return _weaponType; }
      set { _weaponType = value; }
    }
    private int _amorType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"amorType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int amorType
    {
      get { return _amorType; }
      set { _amorType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AccountInfoComponent")]
  public partial class AccountInfoComponent : global::ProtoBuf.IExtensible
  {
    public AccountInfoComponent() {}
    
    private string _unick;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"unick", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string unick
    {
      get { return _unick; }
      set { _unick = value; }
    }
    private int _level;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _job;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"job", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int job
    {
      get { return _job; }
      set { _job = value; }
    }
    private string _position;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string position
    {
      get { return _position; }
      set { _position = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ShapeComponent")]
  public partial class ShapeComponent : global::ProtoBuf.IExtensible
  {
    public ShapeComponent() {}
    
    private float _height;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"height", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float height
    {
      get { return _height; }
      set { _height = value; }
    }
    private float _R;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"R", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float R
    {
      get { return _R; }
      set { _R = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Vector3Component")]
  public partial class Vector3Component : global::ProtoBuf.IExtensible
  {
    public Vector3Component() {}
    
    private float _x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private float _z;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float z
    {
      get { return _z; }
      set { _z = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TransformComponent")]
  public partial class TransformComponent : global::ProtoBuf.IExtensible
  {
    public TransformComponent() {}
    
    private Vector3Component _position;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Vector3Component position
    {
      get { return _position; }
      set { _position = value; }
    }
    private float _eulerAngleY;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"eulerAngleY", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float eulerAngleY
    {
      get { return _eulerAngleY; }
      set { _eulerAngleY = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameEvent")]
  public partial class GameEvent : global::ProtoBuf.IExtensible
  {
    public GameEvent() {}
    
    private int _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private float _x = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y = default(float);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private long _playerId = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqNavToPoint")]
  public partial class ReqNavToPoint : global::ProtoBuf.IExtensible
  {
    public ReqNavToPoint() {}
    
    private GameEvent _opt;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"opt", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public GameEvent opt
    {
      get { return _opt; }
      set { _opt = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResNavToPoint")]
  public partial class ResNavToPoint : global::ProtoBuf.IExtensible
  {
    public ResNavToPoint() {}
    
    private int _status;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResAStarSync")]
  public partial class ResAStarSync : global::ProtoBuf.IExtensible
  {
    public ResAStarSync() {}
    
    private int _state;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int state
    {
      get { return _state; }
      set { _state = value; }
    }
    private TransformComponent _transformInfo = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"transformInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public TransformComponent transformInfo
    {
      get { return _transformInfo; }
      set { _transformInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ServerEventNav")]
  public partial class ServerEventNav : global::ProtoBuf.IExtensible
  {
    public ServerEventNav() {}
    
    private GameEvent _optType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"optType", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public GameEvent optType
    {
      get { return _optType; }
      set { _optType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqJoyStickOpt")]
  public partial class ReqJoyStickOpt : global::ProtoBuf.IExtensible
  {
    public ReqJoyStickOpt() {}
    
    private GameEvent _optType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"optType", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public GameEvent optType
    {
      get { return _optType; }
      set { _optType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResJoyStickOpt")]
  public partial class ResJoyStickOpt : global::ProtoBuf.IExtensible
  {
    public ResJoyStickOpt() {}
    
    private int _status;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ServerEventMonster")]
  public partial class ServerEventMonster : global::ProtoBuf.IExtensible
  {
    public ServerEventMonster() {}
    
    private readonly global::System.Collections.Generic.List<MonsterEntity> _monsters = new global::System.Collections.Generic.List<MonsterEntity>();
    [global::ProtoBuf.ProtoMember(1, Name=@"monsters", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MonsterEntity> monsters
    {
      get { return _monsters; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MonsterEntity")]
  public partial class MonsterEntity : global::ProtoBuf.IExtensible
  {
    public MonsterEntity() {}
    
    private long _monsterId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"monsterId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long monsterId
    {
      get { return _monsterId; }
      set { _monsterId = value; }
    }
    private int _state;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int state
    {
      get { return _state; }
      set { _state = value; }
    }
    private MonsterInfoComponent _monsterInfo;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"monsterInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public MonsterInfoComponent monsterInfo
    {
      get { return _monsterInfo; }
      set { _monsterInfo = value; }
    }
    private TransformComponent _transformInfo;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"transformInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public TransformComponent transformInfo
    {
      get { return _transformInfo; }
      set { _transformInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MonsterInfoComponent")]
  public partial class MonsterInfoComponent : global::ProtoBuf.IExtensible
  {
    public MonsterInfoComponent() {}
    
    private long _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _hp;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    private int _maxHp;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"maxHp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int maxHp
    {
      get { return _maxHp; }
      set { _maxHp = value; }
    }
    private int _attack;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"attack", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int attack
    {
      get { return _attack; }
      set { _attack = value; }
    }
    private int _def;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"def", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int def
    {
      get { return _def; }
      set { _def = value; }
    }
    private long _exp;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private float _speed;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"speed", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float speed
    {
      get { return _speed; }
      set { _speed = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MonsterSyncToClientMsg")]
  public partial class MonsterSyncToClientMsg : global::ProtoBuf.IExtensible
  {
    public MonsterSyncToClientMsg() {}
    
    private int _state;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int state
    {
      get { return _state; }
      set { _state = value; }
    }
    private long _monsterId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"monsterId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long monsterId
    {
      get { return _monsterId; }
      set { _monsterId = value; }
    }
    private TransformComponent _transformInfo;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"transformInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public TransformComponent transformInfo
    {
      get { return _transformInfo; }
      set { _transformInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MonsterNavToPointMsg")]
  public partial class MonsterNavToPointMsg : global::ProtoBuf.IExtensible
  {
    public MonsterNavToPointMsg() {}
    
    private long _monsterId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"monsterId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long monsterId
    {
      get { return _monsterId; }
      set { _monsterId = value; }
    }
    private Vector3Component _transformInfo;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"transformInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Vector3Component transformInfo
    {
      get { return _transformInfo; }
      set { _transformInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerEntity")]
  public partial class PlayerEntity : global::ProtoBuf.IExtensible
  {
    public PlayerEntity() {}
    
    private long _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private int _state;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int state
    {
      get { return _state; }
      set { _state = value; }
    }
    private AccountInfoComponent _accountInfo;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"accountInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public AccountInfoComponent accountInfo
    {
      get { return _accountInfo; }
      set { _accountInfo = value; }
    }
    private GhostPlayerInfoComponent _ghostInfo;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"ghostInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public GhostPlayerInfoComponent ghostInfo
    {
      get { return _ghostInfo; }
      set { _ghostInfo = value; }
    }
    private EquipmentPropComponent _EquipmentInfo;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"EquipmentInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public EquipmentPropComponent EquipmentInfo
    {
      get { return _EquipmentInfo; }
      set { _EquipmentInfo = value; }
    }
    private TransformComponent _transformInfo;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"transformInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public TransformComponent transformInfo
    {
      get { return _transformInfo; }
      set { _transformInfo = value; }
    }
    private PrivatePlayerInfoComponent _playerInfo = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"playerInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public PrivatePlayerInfoComponent playerInfo
    {
      get { return _playerInfo; }
      set { _playerInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ServerEventAOIPlayer")]
  public partial class ServerEventAOIPlayer : global::ProtoBuf.IExtensible
  {
    public ServerEventAOIPlayer() {}
    
    private readonly global::System.Collections.Generic.List<PlayerEntity> _ghostPlayers = new global::System.Collections.Generic.List<PlayerEntity>();
    [global::ProtoBuf.ProtoMember(1, Name=@"ghostPlayers", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PlayerEntity> ghostPlayers
    {
      get { return _ghostPlayers; }
    }
  
    private long _playerId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GhostPlayerInfoComponent")]
  public partial class GhostPlayerInfoComponent : global::ProtoBuf.IExtensible
  {
    public GhostPlayerInfoComponent() {}
    
    private int _level;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _job;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"job", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int job
    {
      get { return _job; }
      set { _job = value; }
    }
    private float _speed;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"speed", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float speed
    {
      get { return _speed; }
      set { _speed = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PrivatePlayerInfoComponent")]
  public partial class PrivatePlayerInfoComponent : global::ProtoBuf.IExtensible
  {
    public PrivatePlayerInfoComponent() {}
    
    private long _exp;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private int _HP;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"HP", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int HP
    {
      get { return _HP; }
      set { _HP = value; }
    }
    private int _Mp;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Mp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Mp
    {
      get { return _Mp; }
      set { _Mp = value; }
    }
    private int _coin;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"coin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int coin
    {
      get { return _coin; }
      set { _coin = value; }
    }
    private int _money;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int money
    {
      get { return _money; }
      set { _money = value; }
    }
    private int _attack;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"attack", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int attack
    {
      get { return _attack; }
      set { _attack = value; }
    }
    private int _def;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"def", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int def
    {
      get { return _def; }
      set { _def = value; }
    }
    private int _maxHp;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"maxHp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int maxHp
    {
      get { return _maxHp; }
      set { _maxHp = value; }
    }
    private int _maxMp;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"maxMp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int maxMp
    {
      get { return _maxMp; }
      set { _maxMp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerSyncToClient")]
  public partial class PlayerSyncToClient : global::ProtoBuf.IExtensible
  {
    public PlayerSyncToClient() {}
    
    private int _state;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int state
    {
      get { return _state; }
      set { _state = value; }
    }
    private long _playerId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private TransformComponent _transformInfo;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"transformInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public TransformComponent transformInfo
    {
      get { return _transformInfo; }
      set { _transformInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerSync")]
  public partial class PlayerSync : global::ProtoBuf.IExtensible
  {
    public PlayerSync() {}
    
    private int _state;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int state
    {
      get { return _state; }
      set { _state = value; }
    }
    private long _playerId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private TransformComponent _transformInfo;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"transformInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public TransformComponent transformInfo
    {
      get { return _transformInfo; }
      set { _transformInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ServerEventUserOptMsg")]
  public partial class ServerEventUserOptMsg : global::ProtoBuf.IExtensible
  {
    public ServerEventUserOptMsg() {}
    
    private GameEvent _opt;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"opt", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public GameEvent opt
    {
      get { return _opt; }
      set { _opt = value; }
    }
    private int _state;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int state
    {
      get { return _state; }
      set { _state = value; }
    }
    private TransformComponent _transformInfo;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"transformInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public TransformComponent transformInfo
    {
      get { return _transformInfo; }
      set { _transformInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqPlayerAttack")]
  public partial class ReqPlayerAttack : global::ProtoBuf.IExtensible
  {
    public ReqPlayerAttack() {}
    
    private GameEvent _opt;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"opt", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public GameEvent opt
    {
      get { return _opt; }
      set { _opt = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResPlayerAttack")]
  public partial class ResPlayerAttack : global::ProtoBuf.IExtensible
  {
    public ResPlayerAttack() {}
    
    private int _status;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"Module")]
    public enum Module
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"INVALID_MODELUE", Value=0)]
      INVALID_MODELUE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BASE", Value=1)]
      BASE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GM", Value=2)]
      GM = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTICE", Value=3)]
      NOTICE = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN", Value=101)]
      LOGIN = 101,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PLAYER", Value=102)]
      PLAYER = 102,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCENE", Value=103)]
      SCENE = 103,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ACTIVITY", Value=104)]
      ACTIVITY = 104,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SKILL", Value=105)]
      SKILL = 105,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHAT", Value=106)]
      CHAT = 106
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"Cmd")]
    public enum Cmd
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"INVALID_CMD", Value=0)]
      INVALID_CMD = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuestLoginReq", Value=1)]
      GuestLoginReq = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuestLoginRes", Value=2)]
      GuestLoginRes = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UserLoginReq", Value=3)]
      UserLoginReq = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UserLoginRes", Value=4)]
      UserLoginRes = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SelectPlayerReq", Value=5)]
      SelectPlayerReq = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SelectPlayerRes", Value=6)]
      SelectPlayerRes = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RuckSackReq", Value=7)]
      RuckSackReq = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RuckSackRes", Value=8)]
      RuckSackRes = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PutOnEquipmentReq", Value=9)]
      PutOnEquipmentReq = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PutOnEquipmentRes", Value=10)]
      PutOnEquipmentRes = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SellGoodsReq", Value=11)]
      SellGoodsReq = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SellGoodsRes", Value=12)]
      SellGoodsRes = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BuyGoodsWithCoinReq", Value=13)]
      BuyGoodsWithCoinReq = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BuyGoodsWithCoinRes", Value=14)]
      BuyGoodsWithCoinRes = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EnterSceneReq", Value=15)]
      EnterSceneReq = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EnterSceneRes", Value=16)]
      EnterSceneRes = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NavToPointReq", Value=17)]
      NavToPointReq = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NavToPointRes", Value=18)]
      NavToPointRes = 18,
            
      [global::ProtoBuf.ProtoEnum(Name=@"JoyStickOptReq", Value=19)]
      JoyStickOptReq = 19,
            
      [global::ProtoBuf.ProtoEnum(Name=@"JoyStickOptRes", Value=20)]
      JoyStickOptRes = 20,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ePlayerAttackReq", Value=21)]
      ePlayerAttackReq = 21,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ePlayerAttackRes", Value=22)]
      ePlayerAttackRes = 22,
            
      [global::ProtoBuf.ProtoEnum(Name=@"XL_PlayerSync", Value=998)]
      XL_PlayerSync = 998,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ServerEventUserOpt", Value=999)]
      ServerEventUserOpt = 999,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ServerEventAOIMonster", Value=1000)]
      ServerEventAOIMonster = 1000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MonsterSyncToClient", Value=1001)]
      MonsterSyncToClient = 1001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MonsterNavToPoint", Value=1002)]
      MonsterNavToPoint = 1002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eServerEventAOIPlayer", Value=1003)]
      eServerEventAOIPlayer = 1003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ePlayerSyncToClient", Value=1004)]
      ePlayerSyncToClient = 1004
    }
  
}